### ISSUE TITLE
Navigating to atom feed opens feed reader instead of viewing it in the browser.

### ISSUE THREAD

**Issue by bcomnes** [sergeche/xmlview#49] opened 2014-03-19 21:26 UTC
Not sure if this is something we have control over, but it is preventing me from viewing XML feed files directly in the browser.  

Note: This is only an issue in safari as far as I can tell.
##

**Comment by riconeitzel** [comment] 2016-06-14 10:00
It's a duplicate of #51 – I'm sure

**Closed** 2016-12-20 19:54 UTC
